name: Release Mod

on:
  push:
    tags:
      - "v*"

jobs:
  gradle-publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup JDKs
        uses: actions/setup-java@v4
        with:
          java-version: |
            16
            17
            21
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        with:
          arguments: publish

  github-release:
    needs: gradle-publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Release
        uses: softprops/action-gh-release@v1
